# Generated by Django 4.1.4 on 2023-04-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("authorname", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("duration", models.FloatField()),
            ],
        ),
    ]
